name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: TheClusterFlux/central-workflows/.github/workflows/DockerBuildAndK8Deploy.yaml@main
    secrets: 
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
    